
###This is demo only

#linux-arm64:
 #machine:
    #image: ubuntu-2024:202101-01
    #resource_class: arm.medium
    #environment:
      - #OPM_NUM_THREADS: 2
      - #OPENBLAS_NUM_THREADS: 2
      - #CONDA_ENV_NAME: testenv
